## YAML Template.
sudo: required
language: java
jdk:
- oraclejdk8
services:
- mysql
- docker
dist: trusty
addons:
apt:
packages:
- mysql-server-5.7
- mysql-client-core-5.7
- mysql-client-5.7
before_script:
- mysql -u root -e 'CREATE DATABASE empleado;'
- mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
- mysql -u root -e "GRANT ALL ON empleado.* TO 'sa'@'localhost';"


before_install:
# install heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- chmod +x mvnw
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD registry.heroku.com

script:
- cd bootdocker
- docker build -t 1001233/lab7 .
- docker tag 1001233/lab7 registry.heroku.com/$HEROKU_APP_NAME/web
deploy:   
  provider: heroku
  api_key:
    secure: e4538a22-4aec-4c71-9ebc-1de9670530c4
  app: empleados12
